### ISSUE TITLE
Installation on civicrm version 4.6 causes error.

### ISSUE THREAD

**Issue by knockiiing** [VishalAgarwal/CiviWebExtension#2]
After installing the web tracking extension on civicrm version 4.6, i was able to access event manager. Folloinwing is received. I had to disabled the extension in order to user the event manager again:
backTrace
#0 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Core/Error.php(182): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: no such table", -18, 16, (Array:2), "SELECT \* \n FROM civicrm_webtracking \n \n WHERE (  civicrm_webtracking.page_...")
#4 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-18, 16, (Array:2), "SELECT \* \n FROM civicrm_webtracking \n \n WHERE (  civicrm_webtracking.page_...")
#5 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -18, NULL, NULL, "SELECT \* \n FROM civicrm_webtracking \n \n WHERE (  civicrm_webtracking.page_...", "DB_Error", TRUE)
#6 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB/mysql.php(899): DB_common->raiseError(-18, NULL, NULL, NULL, "1146 *\* Table 'k00011db01.civicrm_webtracking' doesn't exist")
#7 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("SELECT \* \n FROM civicrm_webtracking \n \n WHERE (  civicrm_webtracking.page_...")
#9 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("SELECT \* \n FROM civicrm_webtracking \n \n WHERE (  civicrm_webtracking.page_...")
#10 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/packages/DB/DataObject.php(441): DB_DataObject->_query("SELECT \* \n FROM civicrm_webtracking \n \n WHERE (  civicrm_webtracking.page_...")
#11 /mnt/nfs/staging/k00011/civicrm_extensions/org.civicrm.webtracking-master/CRM/WebTracking/BAO/WebTracking.php(62): DB_DataObject->find(TRUE)
#12 /mnt/nfs/staging/k00011/civicrm_extensions/org.civicrm.webtracking-master/webtracking.php(163): CRM_WebTracking_BAO_WebTracking::retrieve((Array:2), NULL)
#13 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook.php(211): webtracking_civicrm_tabset("civicrm/event/manage/rows", (Array:1), (Array:1))
#14 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(87): CRM_Utils_Hook->runHooks((Array:67), "civicrm_tabset", 3, "civicrm/event/manage/rows", (Array:1), (Array:1), NULL, NULL, NULL)
#15 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Utils/Hook.php(664): CRM_Utils_Hook_DrupalBase->invoke(3, "civicrm/event/manage/rows", (Array:1), (Array:1), NULL, NULL, NULL, "civicrm_tabset")
#16 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Event/Page/ManageEvent.php(385): CRM_Utils_Hook::tabset("civicrm/event/manage/rows", (Array:1), (Array:1))
#17 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Event/Page/ManageEvent.php(239): CRM_Event_Page_ManageEvent->browse()
#18 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Event_Page_ManageEvent->run((Array:3), NULL)
#19 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#20 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#21 /mnt/nfs/staging/k00011/htdocs/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#22 [internal function](): civicrm_invoke("event", "manage")
#23 /mnt/nfs/staging/k00011/htdocs/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2))
#24 /mnt/nfs/staging/k00011/htdocs/index.php(21): menu_execute_active_handler()
#25 {main}

Sorry but we are not able to provide this at the moment. 

Kindly assist.

**Comment by VishalAgarwal** [comment]
Hi,

I am looking into it. Will get back to you once I figure it out.

For some reason the extension is not able to either create or use the new table (civicrm_webtracking) in the database. It does not give an error on my computer. This suggests that there is some issue with the permissions.

Thanks,
Vishal Agarwal

**Comment by knockiiing** [comment]
Hi Vishal, any chance of getting feedback on this? Or as alternative can we bypass this civicrm extension solution and go for a Drupal Google analysis module? Thanks

**Comment by VishalAgarwal** [comment]
Hi,

Could you please share the configuration of your CiviCRM installation.
I will be able to resolve this post 15th December, 2015.

**Comment by tttp** [comment]
Hi @VishalAgarwal, any progress on that issue?

**Comment by knockiiing** [comment]
Hey X, we will be linking up tomorrow after work, right?

**Comment by tttp** [comment]
@VishalAgarwal it seems that the install doesn't create the table, trying to add it by hand see how it goes, but I confirm the report: not working out of the box

**Comment by VishalAgarwal** [comment]
Hey Xavier, 
I have a auto_install script which is similar to the one being used by other standard extensions like CiviVolunteer. Could you please try to install CiviVolunteer and see if the appropriate tables gets created.

I had personally used the build kit to set up CiviCRM on my machine. The install does create the table on my machine. Could you guide me as to how should i proceed to reproduce the same error on my machine?

**Comment by mlutfy** [comment]
I haven't extensively tested this extension yet, but I submitted a PR to fix the installation issue: https://github.com/VishalAgarwal/org.civicrm.webtracking/pull/3
